### ISSUE TITLE
Config files for Adaption algorithms

### ISSUE THREAD

**Issue by RafLaf** [Frankluox/Pytorch-MetaDataset#1]
Hello,

Thank you for your contribution. I would like to reproduce the results of the Table 1 in your paper. For now, I only work with evaluation/finetune_res12_CE.yaml which is limited to finetune. Do you have the config files to compare the Adaptation algorithms at test time (MatchingNet, MetaOpt, NCC, LR, URL, CC, TSA/eTT)? It would also be nice to have your configs for all Training algorithms but it is less important to me. 

Thank you very much in advance. 
Have a great day and Happy New Year !

**Comment by Frankluox** [comment]
Hi, please refer to `write_yaml_test.py` for all configurations of test-time algorithms (lines 104-120). Feel free to contact me if you have any further questions.

**Comment by RafLaf** [comment]
Thank you!
