### ISSUE TITLE
About CLIP

### ISSUE THREAD

**Issue by yiyuyuyi** [Frankluox/Pytorch-MetaDataset#3]
Hi, your work is truly inspiring! Could you please clarify if you used the text encoder in CLIP? If so, how did you generate the text labels for each episode?

**Comment by Frankluox** [comment]
Hi, we do not use the text encoder of CLIP and only use the image encoder in the same way as other visual encoders without using the exact text labels.

**Comment by yiyuyuyi** [comment]
> Hi, we do not use the text encoder of CLIP and only use the image encoder in the same way as other visual encoders without using the exact text labels.

Thank you a lot !
